name: Verify
on:
  workflow_call: # Can be called from other workflows

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check types
        run: deno check src/**/*.ts
      - name: Lint code
        run: deno lint
      - name: Check formatting
        run: deno fmt --check
